DATA:
  DIM: 2                  # data dimension
  BATCH_SIZE: 32 #16
  TEST_BATCH_SIZE: 32 #16
  DATA_PATH: './data/spacenet3/train_data_128_dense/'        # Path to dataset, could be overwritten by command line argument
  TEST_DATA_PATH: './data/spacenet3/test_data_128_dense/'
  VAL_DATA_PATH: './data/spacenet3/test_data_128_dense/'
  DATASET: 'spacenet3'     # Dataset name
  IMG_SIZE: [128, 128]    # Input image size
  NUM_WORKERS: 4          # Number of data loading threads
  SEED: 10                # random seed for reproducibility
  AUGMENTATIONS: True

MODEL:
  NUM_CLASSES: 2          # Number of classes, overwritten in data preparation
  SEG: False
  EDGE_DESCRIPTORS: True
  PYRAMID_DESCRIPTORS: False

  ENCODER:
    TYPE: deformable_transformer_backbone
    NAME: deformable_transformer_backbone
    HIDDEN_DIM: 256 #128 #256 #768
    POSITION_EMBEDDING: sine
    LR_BACKBONE: 2e-5
    NUM_FEATURE_LEVELS: 4
    BACKBONE: resnet50
    MASKS: False
    DILATION: False

    # parameters used else where
    IN_CHANS: 3
    DEPTHS: [4, 4, 8, 8, 18]

  DECODER:
    TYPE: deformable_transformer
    NAME: deformable_transformer
    HIDDEN_DIM: 256 #128 #256 #768
    NHEADS: 8
    ENC_LAYERS: 4 #4 #2
    DEC_LAYERS: 4 #4 #2
    DIM_FEEDFORWARD: 512 #128 #512 #2048
    DROPOUT: 0.1  # 0.0
    ACTIVATION: relu  
    NUM_FEATURE_LEVELS: 4
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    TWO_STAGE: True
    TWO_STAGE_TYPE: 'dino_gnn' # detr, dino, poly
    APPEND_LOC: True
    AUX_LOSS: True
    WITH_BOX_REFINE: True

    OBJ_TOKEN: 128
    RLN_TOKEN: 0
    DUMMY_TOKEN: 0

    RLN_ATTN: True # only do comb RLN_ATTN True + RLN_TOKEN 0 and reverse

  MATCHER:
    C_CLASS: 3
    C_NODE: 5
  
  GNN:
    DIRECTED: True

TRAIN:
  EPOCHS: 40
  LR: 2e-4
  LR_BACKBONE: 2e-5
  WEIGHT_DECAY: 1e-4
  LR_DROP: 80
  CLIP_MAX_NORM: 0.1  # hardcoded

  SAVE_PATH: "./work_dirs/gnn"          # save path for the checkpoint, log and val results
  VAL_INTERVAL: 5             # validation interval
  SAVE_VAL: False                   # save validation data

  # loss weight
  LOSSES: ['edges'] # ['boxes', 'class', 'cards', 'nodes', 'edges']
  NUM_EDGES: 80
  W_BBOX: 2.0
  W_CLASS: 3.0
  W_CARD: 1.0
  W_NODE: 5.0
  W_EDGE: 4.0
  MULTI_CLASS: False


log:
  exp_name: 'spacenet3_lanegnn_dig'
  message: "Baseline 2D relationformer for spacenet3"
